// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcmGgFDXicNuhaoSJAgNmkSJFNZwk6gho',
    appId: '1:453564794426:web:e72d4584ce2adc8ae45703',
    messagingSenderId: '453564794426',
    projectId: 'lariku-b5bb4',
    authDomain: 'lariku-b5bb4.firebaseapp.com',
    storageBucket: 'lariku-b5bb4.firebasestorage.app',
    measurementId: 'G-M9KYCSW18Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXNPgkh15ZHT7Lz7eRAYV2wgHYFTI8180',
    appId: '1:453564794426:android:62d4521392bdce8fe45703',
    messagingSenderId: '453564794426',
    projectId: 'lariku-b5bb4',
    storageBucket: 'lariku-b5bb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjqGpyZsRoKh3Qtl8WJQm9mN6H6nl-wpA',
    appId: '1:453564794426:ios:61370a5140d0c87ee45703',
    messagingSenderId: '453564794426',
    projectId: 'lariku-b5bb4',
    storageBucket: 'lariku-b5bb4.firebasestorage.app',
    iosClientId: '453564794426-queph4ag8ii9bpsiipbbe59cpqr6akd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lariku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjqGpyZsRoKh3Qtl8WJQm9mN6H6nl-wpA',
    appId: '1:453564794426:ios:61370a5140d0c87ee45703',
    messagingSenderId: '453564794426',
    projectId: 'lariku-b5bb4',
    storageBucket: 'lariku-b5bb4.firebasestorage.app',
    iosClientId: '453564794426-queph4ag8ii9bpsiipbbe59cpqr6akd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lariku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcmGgFDXicNuhaoSJAgNmkSJFNZwk6gho',
    appId: '1:453564794426:web:99bc92e5e48d6f09e45703',
    messagingSenderId: '453564794426',
    projectId: 'lariku-b5bb4',
    authDomain: 'lariku-b5bb4.firebaseapp.com',
    storageBucket: 'lariku-b5bb4.firebasestorage.app',
    measurementId: 'G-STCSM2N9YD',
  );
}
